extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

env:
  amd: true
  browser: true
  node: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'
  - 'import'
  - 'react'
  - 'react-hooks'
  - 'jsx-a11y'
  - 'prettier'

rules:
  '@typescript-eslint/no-var-requires':
    - 'off'
  import/no-extraneous-dependencies:
    - 'error'
  prettier/prettier:
    - 'error'
