extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/electron'
  - 'plugin:import/typescript'
  - 'prettier'

env:
  browser: true
  es6: true
  node: true

ignorePatterns:
  - 'dist'
  - 'scripts'

parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

plugins:
  - '@typescript-eslint'
  - 'import'
  - 'react'
  - 'react-hooks'
  - 'jsx-a11y'
  - 'prettier'

rules:
  '@typescript-eslint/no-var-requires':
    - 'off'
  import/no-extraneous-dependencies:
    - 'error'
  prettier/prettier:
    - 'error'
